### ISSUE TITLE
How to find out why the results are inconsistent with vllm

### ISSUE THREAD

**Issue by UncleFB** [triton-inference-server/tensorrtllm_backend#77]
The model I'm using is vicuna-13b. 
I tested more than 100 cases, and about 10% of the results of inference on tensorrt-backend are different from the results of inference on vllm. How to find out the specific reason?

All the parameters during vllm inference are here, but I don’t know how to pass them on tensorrt.
`sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, temperature=0.1, top_p=0.35, top_k=-1, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['</s>'], ignore_eos=False, max_tokens=512, logprobs=None, prompt_logprobs=None, skip_special_tokens=True`

**Comment by byshiue** [comment]
The different results of TRT-LLM and vllm are expected because we do many optimization and affect the computation order. Besides, using sampling also leads to different results. 

If you want to see fully same results, you can try running both models on FP32 and use greedy search. From our experience, most outputs should be same under such case.
